stages:
  - stage_a
  - stage_b

job1:
  stage: stage_a
  script:
    - echo 'this is stage a job 1'

job2:
  stage: stage_a
  script:
    - echo 'this is stage a job 2'

# job3:
#   image: postgres:latest
#   stage: stage_b
#   script:
#     - echo 'this is stage b job 3'
#     - psql --version