before_script:
  - echo "begin"
  - cd /git/front
  - git pull

after_script:
  - echo "end"

stages:
  - Test
  - Build

# 构建阶段1
job1:
  stage: Build
  script:
    - npm install 
  tags:
    - test1
# 构建阶段2
job2:
  stage: Test
  script:
    - service nginx reload 
  tags:
    - test    