before_script:
  - echo "begin"
  - pwd
  # - cd /git/front
  - git pull origin develop

after_script:
  - echo "end"

stages:
  - Test
  - Build

# 构建阶段1
job1:
  stage: Build
  script:
    - npm install 
  tags: # 指定使用有 my-tag 标签的runner运行该任务
    - test1
# 构建阶段2
job2:
  stage: Test
  script:
    # - service nginx reload 
  tags:
    - test    